version: '{build}'
branches:
  only:
  - master
  - /^v\d+(?:\.\d+)?$/
  - /[\b_]validate\b/
skip_tags: true
skip_commits:
  files:
    - doc/*
    - .github/*
    - '**/*.md'
    - .vsts-ci.yml
nuget:
  disable_publish_on_pr: true
image: Visual Studio 2017
configuration: Release
environment:
  VisualStudioVersion: 15.0
  TreatWarningsAsErrors: true
  CodeAnalysisTreatWarningsAsErrors: true
init:
- git config --global core.autocrlf true
install:
  appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/v4.6.1/nuget.exe
before_build:
  nuget restore src
build_script:
- msbuild src\Microsoft.VisualStudio.Threading.sln /p:platform="Any CPU" /nologo /m /v:minimal /t:build,pack /bl:msbuild.binlog
- msbuild src\Microsoft.VisualStudio.Threading.sln /p:platform=x64 /nologo /m /v:minimal /bl:msbuild_x64.binlog
- msbuild src\Microsoft.VisualStudio.Threading.sln /p:platform=x86 /nologo /m /v:minimal /bl:msbuild_x86.binlog
test_script:
- >-
    md "bin\%configuration%"

    SET testdir=bin\Microsoft.VisualStudio.Threading.Tests\%configuration%\

    "%xunit20%\xunit.console.x86.exe"
    "bin\Microsoft.VisualStudio.Threading.Tests\%configuration%\net451\Microsoft.VisualStudio.Threading.Tests.dll"
    -noshadow
    -html "bin\%configuration%\testresults_net451.html" -xml "bin\%configuration%\testresults_net451.xml"
    -appveyor
    -notrait "TestCategory=FailsInCloudTest"
    -nologo

    "%xunit20%\xunit.console.x86.exe"
    "bin\Microsoft.VisualStudio.Threading.Tests\%configuration%\net452\Microsoft.VisualStudio.Threading.Tests.dll"
    "bin\Microsoft.VisualStudio.Threading.Analyzers.Tests\%configuration%\net46\Microsoft.VisualStudio.Threading.Analyzers.Tests.dll"
    -noshadow
    -html "bin\%configuration%\testresults_net452.html" -xml "bin\%configuration%\testresults_net452.xml"
    -appveyor
    -notrait "TestCategory=FailsInCloudTest"
    -nologo

    "%xunit20%\xunit.console.x86.exe"
    "bin\Microsoft.VisualStudio.Threading.Tests\%configuration%\net46\Microsoft.VisualStudio.Threading.Tests.dll"
    -noshadow
    -html "bin\%configuration%\testresults_net46.html" -xml "bin\%configuration%\testresults_net46.xml"
    -appveyor
    -notrait "TestCategory=FailsInCloudTest"
    -nologo

    dotnet test src\Microsoft.VisualStudio.Threading.Tests\Microsoft.VisualStudio.Threading.Tests.csproj
    --no-build
    -f netcoreapp1.0
    --filter "TestCategory!=FailsInCloudTest"

    dotnet test src\Microsoft.VisualStudio.Threading.Tests\Microsoft.VisualStudio.Threading.Tests.csproj
    --no-build
    -f netcoreapp2.0
artifacts:
- path: bin\**\*.nupkg
  name: NuGet Package
- path: bin\AsyncDebugTools\x64\$(Configuration)\AsyncDebugTools.dll
  name: WinDbg extension (x64)
- path: bin\AsyncDebugTools\x86\$(Configuration)\AsyncDebugTools.dll
  name: WinDbg extension (x86)
- path: msbuild*.binlog
  name: Build logs
- path: bin\**\testresults*
  name: Test results
