steps:
- task: ms-vseng.MicroBuildShipTasks.7c429315-71ba-4cb3-94bb-f829c95f7915.MicroBuildCodesignVerify@2
  displayName: Verify Signed Files
  inputs:
    TargetFolders: |
      $(Build.SourcesDirectory)/bin/Packages/$(BuildConfiguration)/NuGet

- task: MicroBuildCleanup@1
  condition: and(succeededOrFailed(), ne(variables['Hosted'], 'true'))
  displayName: MicroBuild Cleanup

- task: ms.vss-governance-buildtask.governance-build-task-component-detection.ComponentGovernanceComponentDetection@0
  displayName: Component Detection
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))

- task: ms-vscs-artifact.build-tasks.artifactDropTask-1.artifactDropTask@0
  inputs:
    dropServiceURI: https://devdiv.artifacts.visualstudio.com
    buildNumber: $(ProfilingInputsDropName)
    sourcePath: $(Build.ArtifactStagingDirectory)\OptProf\ProfilingInputs
    toLowerCase: false
    usePat: false
  displayName: Publish to Artifact Services - ProfilingInputs
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))

- task: NuGetCommand@2
  inputs:
    command: push
    searchPatternPush: '$(Build.SourcesDirectory)\bin\**\$(BuildConfiguration)\**\*.nupkg;!**\*.symbols.nupkg;!**/VS.*.nupkg'
    publishVstsFeed: $(feedGuid)
    allowPackageConflicts: true
  displayName: Push packages to VSTS feed
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))

- powershell: |
    $DllPaths = @(
        ,"bin\Microsoft.VisualStudio.Threading\$(BuildConfiguration)\Microsoft.VisualStudio.Threading.dll"
        ,"bin\Microsoft.VisualStudio.Threading.Analyzers.CodeFixes\$(BuildConfiguration)\Microsoft.VisualStudio.Threading.Analyzers.dll"
        ,"bin\Microsoft.VisualStudio.Threading.Analyzers.CodeFixes\$(BuildConfiguration)\Microsoft.VisualStudio.Threading.Analyzers.CodeFixes.dll"
    )
    Get-ChildItem $DllPaths -rec |% {
        $OutputDir = "$($_.Directory.FullName)\symstore"
        if (!(Test-Path $OutputDir)) { mkdir $OutputDir | Out-Null }
        Write-Host "Converting PDB for $_"
        azure-pipelines\Convert-PDB.ps1 -DllPath $_ -OutputPath "$OutputDir\$($_.BaseName).pdb"
    }
  displayName: Converting portable PDBs to Windows PDBs

- task: CopyFiles@1
  inputs:
    SourceFolder: bin
    Contents: |
      Microsoft.VisualStudio.Threading/$(BuildConfiguration)/**/Microsoft.VisualStudio.Threading.dll
      Microsoft.VisualStudio.Threading/$(BuildConfiguration)/**/symstore/Microsoft.VisualStudio.Threading.pdb
      Microsoft.VisualStudio.Threading.Analyzers.CodeFixes/$(BuildConfiguration)/**/Microsoft.VisualStudio.Threading.Analyzers.dll
      Microsoft.VisualStudio.Threading.Analyzers.CodeFixes/$(BuildConfiguration)/**/symstore/Microsoft.VisualStudio.Threading.Analyzers.pdb
      Microsoft.VisualStudio.Threading.Analyzers.CodeFixes/$(BuildConfiguration)/**/Microsoft.VisualStudio.Threading.Analyzers.CodeFixes.dll
      Microsoft.VisualStudio.Threading.Analyzers.CodeFixes/$(BuildConfiguration)/**/symstore/Microsoft.VisualStudio.Threading.Analyzers.CodeFixes.pdb
      AsyncDebugTools/x86/$(BuildConfiguration)/AsyncDebugTools.dll
      AsyncDebugTools/x86/$(BuildConfiguration)/AsyncDebugTools.pdb
      AsyncDebugTools/x64/$(BuildConfiguration)/AsyncDebugTools.dll
      AsyncDebugTools/x64/$(BuildConfiguration)/AsyncDebugTools.pdb
    TargetFolder: $(Build.ArtifactStagingDirectory)/symbols
  displayName: Collecting symbols artifacts

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)/InsertionOutputs
    ArtifactName: InsertionOutputs
    ArtifactType: Container
  displayName: Publish InsertionOutputs as Azure DevOps artifacts
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)/symbols
    ArtifactName: symbols
    ArtifactType: Container
  displayName: Publish symbols as Azure DevOps artifacts

- task: PublishSymbols@2
  inputs:
    SymbolsFolder: $(Build.ArtifactStagingDirectory)/symbols
    SearchPattern: '**/*.pdb'
    IndexSources: false
    SymbolServerType: TeamServices
  displayName: Publish symbols to symbol server
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))

- task: Ref12.ref12-analyze-task.ref12-analyze-task.Ref12Analyze@0
  displayName: Ref12 (Codex) Analyze
  inputs:
    codexoutputroot: $(Build.ArtifactStagingDirectory)\Codex
    workflowArguments: |
      /sourcesDirectory:$(Build.SourcesDirectory)
      /codexRepoUrl:$(Build.Repository.Uri)
      /repoName:$(Build.Repository.Name)
      /additionalCodexArguments:-bld
      /additionalCodexArguments:$(Build.ArtifactStagingDirectory)/build_logs
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  continueOnError: true
