steps:

- task: MicroBuildIBCMergePlugin@0
  inputs:
    branch: $(IBCMergeBranch)
  displayName: Install MicroBuild IBCMerge Plugin
  condition: and(succeeded(), ne(variables['Hosted'], 'true'))

- task: MicroBuildSigningPlugin@1
  inputs:
    signType: $(SignType)
    zipSources: false
  displayName: Install MicroBuild Signing Plugin
  condition: and(succeeded(), ne(variables['Hosted'], 'true'))
