trigger:
  branches:
    include: ["master", "v15.8", "v16.0"]
  paths:
    exclude: [".github", "doc", "*.md", ".appveyor.yml", ".travis.yml"]

variables:
  TreatWarningsAsErrors: true
  UpdateXlfOnBuild: false # force build breaks if xlf files aren't updated on dev box with resx changes
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  BuildConfiguration: Release
  BuildPlatform: Any CPU
  NUGET_PACKAGES: $(Agent.TempDirectory)/.nuget/packages

jobs:
- job: Windows
  pool: VSEng-MicroBuildVS2019
  steps:
  - template: build.yml
